### ISSUE TITLE
Can't create accounts

### ISSUE THREAD

**Issue by brookr** [dcorns/PGP-WEB-APP#69]
When I attempt to create an account, an alert popup seems to prevent the form from submitting. See screenshot:
![screen shot 2015-01-30 at 9 28 14 am](https://cloud.githubusercontent.com/assets/11095/5980169/a3d2352c-a862-11e4-83a6-fd9afb36f356.png)

**Comment by dcorns** [comment]
That is an awful email address and probably causing the heroku failure. "Normal" email address have no problem.
